- This folder contains an analysis that attempts to answer the question on whether or not defense has an impact on team winning percentages. 
- The data for the analysis is the 2019 NCAA College football season. 
- This analysis focused on using Alteryx to answer the research question. 
